# This file was generated by GoReleaser. DO NOT EDIT.
cask "adguardhome-sync" do
  version "0.9.3"

  on_macos do
    on_arm do
      sha256 "11b6d43ce6204b4ab88a437448f1004d952ad90dc31ebe2ec234c975238ce1f1"
      url "https://github.com/bakito/adguardhome-sync/releases/download/v#{version}/adguardhome-sync_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9715f92ca076cffd75bb71457dd8f65273f581fe83a74abe5e3348d9aba0ea1a"
      url "https://github.com/bakito/adguardhome-sync/releases/download/v#{version}/adguardhome-sync_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cb1909ad9f4516cf16e3a06e195f4094c29aa97a1a9418a8edfae352d869098c"
      url "https://github.com/bakito/adguardhome-sync/releases/download/v#{version}/adguardhome-sync_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "eac15cb691c21c188d8435724415f4af8c30535d0658145b2c730a6cdd99d22c"
      url "https://github.com/bakito/adguardhome-sync/releases/download/v#{version}/adguardhome-sync_#{version}_linux_amd64.tar.gz"
    end
  end

  name "adguardhome-sync"
  desc "Synchronize AdGuard Home config to replicas"
  homepage "https://github.com/bakito/adguardhome-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "adguardhome-sync"

  # No zap stanza required
end
