# This file was generated by GoReleaser. DO NOT EDIT.
cask "adguardhome-sync" do
  version "0.9.1"

  on_macos do
    on_intel do
      sha256 "2db8ebcc86babf562f2f9fa1567d39a21a799d1f976617d1efd0620f23f2966e"
      url "https://github.com/bakito/adguardhome-sync/releases/download/v#{version}/adguardhome-sync_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f7b36b79e7e1dbccd8b5e8b36081326ed4fece5ae015b1ee386a6d6c25d47c7e"
      url "https://github.com/bakito/adguardhome-sync/releases/download/v#{version}/adguardhome-sync_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ca6cf829a12baacb8500c018ac82b8b86d6b261673e65d3b7672c4939510782c"
      url "https://github.com/bakito/adguardhome-sync/releases/download/v#{version}/adguardhome-sync_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7783abe436d7e3fc7015524963b48b115342ceed35818eaa73e6facdc3afc8ec"
      url "https://github.com/bakito/adguardhome-sync/releases/download/v#{version}/adguardhome-sync_#{version}_linux_arm64.tar.gz"
    end
  end

  name "adguardhome-sync"
  desc "Synchronize AdGuard Home config to replicas"
  homepage "https://github.com/bakito/adguardhome-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "adguardhome-sync"

  # No zap stanza required

end
