# This file was generated by GoReleaser. DO NOT EDIT.
cask "adguardhome-sync" do
  version "0.9.4"

  on_macos do
    on_arm do
      sha256 "ee8529cba4230cb639cd6ba954a236ad6cc6bf91ea2b91ab9f9d9b2529f2a0ab"
      url "https://github.com/bakito/adguardhome-sync/releases/download/v#{version}/adguardhome-sync_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "27162658d1ecc91d5c1047ea8ecabd8e77ef3f5f763accce42637cfa67b6e4c2"
      url "https://github.com/bakito/adguardhome-sync/releases/download/v#{version}/adguardhome-sync_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5e376ae27496e334f4d067725b3ca9bc048392df7701ed089238e3cbe6531024"
      url "https://github.com/bakito/adguardhome-sync/releases/download/v#{version}/adguardhome-sync_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b451d31054d912c2973bda5793ec6f538ab834e335e71d959f1561cf75b2c9de"
      url "https://github.com/bakito/adguardhome-sync/releases/download/v#{version}/adguardhome-sync_#{version}_linux_amd64.tar.gz"
    end
  end

  name "adguardhome-sync"
  desc "Synchronize AdGuard Home config to replicas"
  homepage "https://github.com/bakito/adguardhome-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "adguardhome-sync"

  # No zap stanza required
end
