# This file was generated by GoReleaser. DO NOT EDIT.
cask "kube-metrics" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "18070d71480592b48e116729390b674b401cf2af8b29ab010789bb100e2267e9"
      url "https://github.com/bakito/kube-metrics/releases/download/v#{version}/kube-metrics_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e7c3c756887b2d521c62321bf8711cf8ea37707daa8e25da683295f4b45b3b38"
      url "https://github.com/bakito/kube-metrics/releases/download/v#{version}/kube-metrics_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "38813974b38ae103fab418b007a2ea31a6adcc79c8305ede5d24a62278f76149"
      url "https://github.com/bakito/kube-metrics/releases/download/v#{version}/kube-metrics_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "817ec94e06555518309a6a9a4f89956bb2084e8e30ce37c6255616d714cec2ee"
      url "https://github.com/bakito/kube-metrics/releases/download/v#{version}/kube-metrics_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kube-metrics"
  desc "CLI visualizations of kubernetes pod and node metrics"
  homepage "https://github.com/bakito/kube-metrics"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kube-metrics"

  # No zap stanza required

end
