# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubexporter" do
  version "0.9.1"

  on_macos do
    on_intel do
      sha256 "51a5a57339ad54f0b44324cef00f4b6369fdcabc789a78cf59753b00afb9d822"
      url "https://github.com/bakito/kubexporter/releases/download/v#{version}/kubexporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "034b47860d018b83b7f841c1855c8dca57057196d3b0b1079692eeed1c8a49d6"
      url "https://github.com/bakito/kubexporter/releases/download/v#{version}/kubexporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a3a0adcbb3851ec4130a0c12bca50d42b02706c2d71759ad2b6474b9f68dba0d"
      url "https://github.com/bakito/kubexporter/releases/download/v#{version}/kubexporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f8869a8d5bb07cac1122d6e4f8b70393c8dc4e0ac989b334863fad9b9abbf461"
      url "https://github.com/bakito/kubexporter/releases/download/v#{version}/kubexporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kubexporter"
  desc "Export Kubernetes resources for backup and migration."
  homepage "https://github.com/bakito/kubexporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubexporter"

  # No zap stanza required

end
