# This file was generated by GoReleaser. DO NOT EDIT.
cask "kube-metrics" do
  name "kube-metrics"
  desc "CLI visualisations of kubernetes pod and node metrics"
  homepage "https://github.com/bakito/kube-metrics"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kube-metrics"

  on_macos do
    on_intel do
      url "https://github.com/bakito/kube-metrics/releases/download/v#{version}/kube-metrics_#{version}_darwin_amd64.tar.gz"
      sha256 "75e7b64bce9c1df3008b5bb1e965f42eb94d962cfbd2f52e14f78b7f6f698bd0"
    end
    on_arm do
      url "https://github.com/bakito/kube-metrics/releases/download/v#{version}/kube-metrics_#{version}_darwin_arm64.tar.gz"
      sha256 "f536267c551a463a0e7c46931e7ec9be646c581df236d2c59286aa8616ccda9f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bakito/kube-metrics/releases/download/v#{version}/kube-metrics_#{version}_linux_amd64.tar.gz"
      sha256 "d2205322c37f0297429a81e7b4ae9e015779a476abcf74b5c660dac7c54a8118"
    end
    on_arm do
      url "https://github.com/bakito/kube-metrics/releases/download/v#{version}/kube-metrics_#{version}_linux_arm64.tar.gz"
      sha256 "205f136ca12f35e893e2fcffd8ca5b7c9a1a6651715dd7eff32a145f04e50b08"
    end
  end

  # No zap stanza required
end
