# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubexporter" do
  name "kubexporter"
  desc "Export Kubernetes resources for backup and migration."
  homepage "https://github.com/bakito/kubexporter"
  version "0.8.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubexporter"

  on_macos do
    on_intel do
      url "https://github.com/bakito/kubexporter/releases/download/v#{version}/kubexporter_#{version}_darwin_amd64.tar.gz"
      sha256 "3cde63919376862a145f88eef5d051c417554e3deb98214ac464e447ec70b8b0"
    end
    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the kubexporter
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bakito/kubexporter/releases/download/v#{version}/kubexporter_#{version}_linux_amd64.tar.gz"
      sha256 "a506614eada8e70e860a10d9b796e1748027cdd7926d1db003178b81b9133e7c"
    end
  end

  # No zap stanza required
end
