# This file was generated by GoReleaser. DO NOT EDIT.
cask "kube-metrics" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "7ae107b8224db12de523651e663f93089a147973043110bdfc6c79235bde802f"
      url "https://github.com/bakito/kube-metrics/releases/download/v#{version}/kube-metrics_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d151377edf174f6f6f5218ade0be508057b85da2961cf85af17784dad1ccd95d"
      url "https://github.com/bakito/kube-metrics/releases/download/v#{version}/kube-metrics_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "99e0e4f9c29bf10872212e7a1c60089e0b93937c5ee9eaa26c72d67154e0b0ac"
      url "https://github.com/bakito/kube-metrics/releases/download/v#{version}/kube-metrics_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "af572e182b2a98d0ae187c5c2212c99557510dacccd5bc1f9876a3e05b879ffd"
      url "https://github.com/bakito/kube-metrics/releases/download/v#{version}/kube-metrics_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kube-metrics"
  desc "CLI visualizations of kubernetes pod and node metrics"
  homepage "https://github.com/bakito/kube-metrics"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kube-metrics"

  # No zap stanza required

end
