# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubexporter" do
  name "kubexporter"
  desc "Export Kubernetes resources for backup and migration."
  homepage "https://github.com/bakito/kubexporter"
  version "0.8.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubexporter"

  on_macos do
    on_intel do
      url "https://github.com/bakito/kubexporter/releases/download/v#{version}/kubexporter_#{version}_darwin_amd64.tar.gz"
      sha256 "044c38022b06e76d82e0ca781253ff3a8c002483d7fcc347bab53ff392e0517f"
    end
    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the kubexporter
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bakito/kubexporter/releases/download/v#{version}/kubexporter_#{version}_linux_amd64.tar.gz"
      sha256 "a87668be94ad673d0848671387def317e479fe6d7e6b820ce058e142a82e0599"
    end
  end

  # No zap stanza required
end
