# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolbox" do
  name "toolbox"
  desc "A little toolbox to help fetching tools"
  homepage "https://github.com/bakito/toolbox"
  version "0.4.26"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolbox"

  on_macos do
    on_intel do
      url "https://github.com/bakito/toolbox/releases/download/v#{version}/toolbox_#{version}_darwin_amd64.tar.gz"
      sha256 "bb18ac2e1c6ebdbc07c1dee5fa79ed2543879d7832e8c77b5f6c058d825ebe20"
    end
    on_arm do
      url "https://github.com/bakito/toolbox/releases/download/v#{version}/toolbox_#{version}_darwin_arm64.tar.gz"
      sha256 "21e0f2afa20333c126f214d7e975683083abe140cd1a8f654ce027776b0a8cad"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bakito/toolbox/releases/download/v#{version}/toolbox_#{version}_linux_amd64.tar.gz"
      sha256 "d0d3e311efdc98c9d42decfa9fe818ecdeb95061827a33190dde5a95f839992c"
    end
    on_arm do
      url "https://github.com/bakito/toolbox/releases/download/v#{version}/toolbox_#{version}_linux_arm64.tar.gz"
      sha256 "00fd9da85819886ceeb2b47f725d063f920def49ed1095c65fae13f9bf902b1e"
    end
  end

  # No zap stanza required
end
