# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolbox" do
  name "toolbox"
  desc "A little toolbox to help fetching tools"
  homepage "https://github.com/bakito/toolbox"
  version "0.4.27"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolbox"

  on_macos do
    on_intel do
      url "https://github.com/bakito/toolbox/releases/download/v#{version}/toolbox_#{version}_darwin_amd64.tar.gz"
      sha256 "1d70a75ef5bba797b0b69b037ac1d8787bf428c4a24f09e877d9ea93ec7066c9"
    end
    on_arm do
      url "https://github.com/bakito/toolbox/releases/download/v#{version}/toolbox_#{version}_darwin_arm64.tar.gz"
      sha256 "1c9ffee51c89618e988e0d23c97efb4061b700a1e2480b1fc7c9203960fef74a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bakito/toolbox/releases/download/v#{version}/toolbox_#{version}_linux_amd64.tar.gz"
      sha256 "82ea7e047801bfe3f5132a72cc1951c1c6ca0aa2a7ef76f0c0e2ceb48a016f81"
    end
    on_arm do
      url "https://github.com/bakito/toolbox/releases/download/v#{version}/toolbox_#{version}_linux_arm64.tar.gz"
      sha256 "c3684c941c0e0f056ddb68c5dfc8c3c0dbe837be645bfcb236ae8a0cf2dd6c84"
    end
  end

  # No zap stanza required
end
