# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolbox" do
  name "toolbox"
  desc "A little toolbox to help fetching tools"
  homepage "https://github.com/bakito/toolbox"
  version "0.4.23"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolbox"

  on_macos do
    on_intel do
      url "https://github.com/bakito/toolbox/releases/download/v#{version}/toolbox_#{version}_darwin_amd64.tar.gz"
      sha256 "7530fcf3ec44f8182567065ca7137732de2a10b8087260f47c041d37454d7f18"
    end
    on_arm do
      url "https://github.com/bakito/toolbox/releases/download/v#{version}/toolbox_#{version}_darwin_arm64.tar.gz"
      sha256 "dfdc244ba1632cedc9a6721de562ae83d2e75e072b09560845d1cd86278ec5e0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bakito/toolbox/releases/download/v#{version}/toolbox_#{version}_linux_amd64.tar.gz"
      sha256 "73e56ddee9b543a7e96bcb842675eb5d1343283dc4e0389ca2727488606fa0e7"
    end
    on_arm do
      url "https://github.com/bakito/toolbox/releases/download/v#{version}/toolbox_#{version}_linux_arm64.tar.gz"
      sha256 "e9551ea0f4839a6e6c2a4b595768c47e1c42765d63ec45a66a2e920c4b196202"
    end
  end

  # No zap stanza required
end
